import "./globals.css";
import type { Metadata } from "next";
import { Caveat, Comfortaa, Geist, Geist_Mono, Great_Vibes, Pattaya } from "next/font/google";
import Image from "next/image";
import Link from "next/link"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Comfortaa_var = Comfortaa({
  weight: "variable",
  subsets: ["latin"],
});

const CaveatMono = Caveat({
  weight: "variable",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="font-[Comfortaa] bg-[#5d2e3d]">
          <div className="flex flex-wrap justify-center items-center pt-5 mb-5 max-w-300 mx-auto">
            <Link href="/" className="flex items-center justify-between p-1 pl-4 pr-4 rounded-2xl hover:bg-[#6e3b4b] duration-300">
              <Image src="/MainLogo.svg" className="" width={30} height={30} alt="" />
              <h1 className="text-[15px] font-[caveat] pl-3">КОФЕЙНЫЙ<br />ДВОРИК</h1>
            </Link>
            
            <ul className="flex justify-around text-2xl w-150 shrink-0 gap-4">
              <Link href="/about"><li className="hover:bg-[#6e3b4b] pl-4 pr-4 pt-1 pb-1 duration-300 rounded-2xl">О нас</li></Link>
              <Link href="/menu"><li className="hover:bg-[#6e3b4b] pl-4 pr-4 pt-1 pb-1 duration-300 rounded-2xl">Меню</li></Link>
              <Link href="/about"><li className="hover:bg-[#6e3b4b] pl-4 pr-4 pt-1 pb-1 duration-300 rounded-2xl">Контакты</li></Link>
            </ul>
          </div>
          <div className="bg-[#6e3b4b]">
            <h1 className="text-center h-10 text-[20px] text-[#ffffff] font-[caveat] content-center">ВКУСЫ МИРА В КАЖДОЙ КАПЛЕ</h1>
          </div>
        </header>
        
        <main className="min-h-screen">
          {children}
        </main>

        <footer className="flex p-5 font-[Comfortaa] text-center justify-end items-center bg-[#6e3b4b]">
          <div className="pr-4">КОФЕЙНЫЙ ДВОРИК</div>
          <div className="text-[12px] font-extralight">Кофе для человеков</div>
        </footer>
      </body>
    </html>
  );
}